dreport: Changing bmc dump name
Change:
-Keeping common name across hence changing the bmc dump name
from obmcdump_00000000_1621500754.tar.xz to
BMCDUMP.13F4530.00000000.20220320182233
i.e. BMCDUMP.<serial number>.<dump Id>.<time stamp>

Tested:
Post change dump getting generated with name
BMCDUMP.13F4530.00000000.20220320182233

Signed-off-by: Chirag Sharma <chirshar@in.ibm.com>
Change-Id: I887fe76c508a377e209c74c8249082150ef544f4

diff --git a/tools/dreport.d/dreport b/tools/dreport.d/dreport
--- a/tools/dreport.d/dreport
+++ b/tools/dreport.d/dreport
@@ -13,6 +13,8 @@ usage: dreport [OPTION]
 Options:
         -n, —-name <name>     Name to be used for the archive.
                               Default name format obmcdump_<id>_<epochtime>
+                              For dumps having header, the name format is
+                              BMCDUMP.<serial number>.<id>.<time>
         -d, —-dir <directory> Archive directory to copy the compressed report.
                               Default output directory is /tmp
         -i, —-id <id>         Dump identifier to associate with the archive.
@@ -38,7 +40,6 @@ Options:
 #CONSTANTS
 declare -rx TRUE=1
 declare -rx FALSE=0
-declare -rx UNLIMITED="unlimited"
 declare -rx SUMMARY_DUMP="summary"
 declare -rx TYPE_USER="user"
 declare -rx TYPE_CORE="core"
@@ -49,18 +50,10 @@ declare -rx SUMMARY_LOG="summary.log"
 declare -rx DREPORT_LOG="dreport.log"
 declare -rx TMP_DIR="/tmp"
 declare -rx EPOCHTIME=$(date +"%s")
-declare -rx TIME_STAMP="date -u"
 declare -rx PLUGIN="pl_"
 declare -rx DREPORT_SOURCE="/usr/share/dreport.d"
-declare -rx DREPORT_INCLUDE="$DREPORT_SOURCE/include.d"
 declare -rx ZERO="0"
 declare -rx JOURNAL_LINE_LIMIT="500"
-declare -rx HEADER_EXTENSION="$DREPORT_INCLUDE/gendumpheader"
-
-#Error Codes
-declare -rx SUCCESS="0"
-declare -rx INTERNAL_FAILURE="1"
-declare -rx RESOURCE_UNAVAILABLE="2"
 
 #VARIABLES
 declare -x name=""
@@ -69,7 +62,7 @@ declare -x dump_id="00000000"
 declare -x dump_type=$TYPE_USER
 declare -x verbose=$FALSE
 declare -x quiet=$FALSE
-declare -x dump_size="unlimited"
+declare -x valid_size="unlimited"
 declare -x name_dir=""
 declare -x optional_path=""
 declare -x dreport_log=""
@@ -77,8 +70,10 @@ declare -x summary_log=""
 declare -x cur_dump_size=0
 declare -x pid=$ZERO
 declare -x elog_id=""
+declare -x dump_size="unlimited"
 
 #Source dreport common functions
+. $DREPORT_SOURCE/dcommon
 . $DREPORT_INCLUDE/functions
 
 # @brief Initiate data collection based on the type.
@@ -165,7 +160,11 @@ function set_elog_pid()
 # @brief Initial version of the summary log
 init_summary()
 {
-   log_summary "Name:          $name.tar.xz"
+   if [ -f "$HEADER_EXTENSION" ]; then
+       log_summary "Name:          $name"
+   else
+       log_summary "Name:          $name.tar.xz"
+   fi
    log_summary "Epochtime:     $EPOCHTIME"
    log_summary "ID:            $dump_id"
    log_summary "Type:          $dump_type"
@@ -179,7 +178,12 @@ function initialize()
 {
     #Dump file name
     if [ -z $name ]; then
-        name=$"obmcdump_"$dump_id"_$EPOCHTIME"
+        if [ -f "$HEADER_EXTENSION" ]; then
+            dump_id=$(printf %08d $dump_id)
+            name="BMCDUMP.${serialNo}.${dump_id}.${dDay}"
+        else
+            name=$"obmcdump_"$dump_id"_$EPOCHTIME"
+        fi
     fi
 
     #Create temporary data directory.
@@ -210,11 +214,11 @@ function initialize()
 
     #Size
     #Check the input is integer.
-    if [ "$dump_size" -eq "$dump_size" ] 2>/dev/null; then
+    if [ "$valid_size" -eq "$valid_size" ] 2>/dev/null; then
        #Converts in to bytes.
-       dump_size="$((dump_size * 1024))"
+       valid_size="$((valid_size * 1024))"
     else
-       dump_size=$UNLIMITED
+       valid_size=$UNLIMITED
     fi
 
     return $SUCCESS
@@ -231,42 +235,37 @@ function package()
 
     #tar and compress the files.
     if [ -f "$HEADER_EXTENSION" ]; then
-        tar -Jcf "$name_dir.tar.xz" -C \
-                 $(dirname "$name_dir") $(basename "$name_dir")
-        echo "Adding Dump Header :"$HEADER_EXTENSION
-        ("$HEADER_EXTENSION")
-        cat "$name_dir.tar.xz" | tee -a "/tmp/dumpheader_$EPOCHTIME" > /dev/null
-        mv "/tmp/dumpheader_$EPOCHTIME" "$name_dir.tar.xz"
+        ("$CUSTOM_PACKAGE")
     else
         tar -Jcf "$name_dir.tar.xz" -C \
                  $(dirname "$name_dir") $(basename "$name_dir")
-    fi
 
-    if [ $? -ne 0 ]; then
-        echo $($TIME_STAMP) "Could not create the compressed tar file"
+        if [ $? -ne 0 ]; then
+            echo $($TIME_STAMP) "Could not create the compressed tar file"
+            rm -r "$name_dir"
+            return $INTERNAL_FAILURE
+        fi
+
+        #remove the temporary name specific directory
         rm -r "$name_dir"
-        return $INTERNAL_FAILURE
-    fi
 
-    #remove the temporary name specific directory
-    rm -r "$name_dir"
+        echo $($TIME_STAMP) "Report is available in $dump_dir"
 
-    echo $($TIME_STAMP) "Report is available in $dump_dir"
+        if [ "$TMP_DIR" == "$dump_dir" ] || [ "$TMP_DIR/" == "$dump_dir" ]; then
+            return $SUCCESS
+        fi
 
-    if [ "$TMP_DIR" == "$dump_dir" ] || [ "$TMP_DIR/" == "$dump_dir" ]; then
-       return $SUCCESS
-    fi
+        #copy the compressed tar file into the destination
+        cp "$name_dir.tar.xz" "$dump_dir"
+        if [ $? -ne 0 ]; then
+            echo "Failed to copy the $name_dir.tar.xz to $dump_dir"
+            rm "$name_dir.tar.xz"
+            return $INTERNAL_FAILURE
+        fi
 
-    #copy the compressed tar file into the destination
-    cp "$name_dir.tar.xz" "$dump_dir"
-    if [ $? -ne 0 ]; then
-        echo "Failed to copy the $name_dir.tar.xz to $dump_dir"
+        #Remove the temporary copy of the file
         rm "$name_dir.tar.xz"
-        return $INTERNAL_FAILURE
     fi
-
-    #Remove the temporary copy of the file
-    rm "$name_dir.tar.xz"
 }
 
 # @brief Main function
@@ -301,52 +300,11 @@ TEMP=`getopt -o n:d:i:t:s:p:vVqh \
       --long name:,dir:,dumpid:,type:,size:,path:,verbose,version,quiet,help \
       -- "$@"`
 
-if [ $? -ne 0 ]
-then
-    echo "Error: Invalid options"
-    exit 1
-fi
+validate_arg #Check the arguments
 
-eval set -- "$TEMP"
+main #main program
+exit $?
 
-while [[ $# -gt 1 ]]; do
-    key="$1"
-    case $key in
-        -n|--name)
-            name=$2
-            shift 2;;
-        -d|--dir)
-            dump_dir=$2
-            shift 2;;
-        -i|--dumpid)
-            dump_id=$2
-            shift 2;;
-        -t|--type)
-            dump_type=$2
-            shift 2;;
-        -s|--size)
-            dump_size=$2
-            shift 2;;
-        -p|--path)
-            optional_path=$2
-            shift 2;;
-        -v|—-verbose)
-            verbose=$TRUE
-            shift;;
-        -V|--version)
-            shift;;
-        -q|—-quiet)
-            quiet=$TRUE
-            shift;;
-        -h|--help)
-            echo "$help"
-            exit;;
-        *) # unknown option
-            log_error "Unknown argument: $1"
-            log_info "$help"
-            exit 1;;
-    esac
-done
 
 main #main program
 exit $?
