OpenPOWER: Initiate a BMC dump with OpenPOWER dumps
A BMC dump is needed to get the complete analysis of the
problem which caused a host dump. Add a call to start a
BMC dump once the collection is completed.

Change-Id: I36a44726e594b014d4b7cb536b0db63d82729bc8
Signed-off-by: Dhruvaraj Subhashchandran <dhruvaraj@in.ibm.com>

diff --git a/tools/dreport.d/openpower.d/opdreport b/tools/dreport.d/openpower.d/opdreport
--- a/tools/dreport.d/openpower.d/opdreport
+++ b/tools/dreport.d/openpower.d/opdreport
@@ -182,6 +182,19 @@ function package()
     return "$SUCCESS"
 }
 
+function initiateBMCDump()
+{
+    bmcDumpPath="$(busctl call xyz.openbmc_project.Dump.Manager \
+               /xyz/openbmc_project/dump/bmc \
+               xyz.openbmc_project.Dump.Create CreateDump a\{sv\} 0)"
+    result=$?
+    if [[ ${result} -ne $SUCCESS ]]; then
+        echo "Error in creating BMC dump associated with system dump"
+    else
+        echo "BMC dump initiated ${bmcDumpPath}"
+    fi
+}
+
 # @brief Main function
 function main()
 {
@@ -205,11 +218,13 @@ function main()
     result=$?
     if [[ ${result} -ne $SUCCESS ]]; then
         echo "$($TIME_STAMP)" "Error: Failed to package, Exiting"
+        exit;
     else
         echo "$($TIME_STAMP)" "Successfully completed"
     fi
 
-    
+    #Initiate a BMC dump to capture the logs from BMC
+    initiateBMCDump
 }
 
 # shellcheck disable=SC2034  # Variable is used elsewhere
